# docker-compose.yml

services:
  app:
    build: .
    container_name: amdd_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"            # Accès via http://localhost:8000
    volumes:
      - ./:/var/www/html       # Montage du code
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_DATABASE: amdd_db
      DB_USERNAME: root
      DB_PASSWORD: root         # ✅ Mot de passe = root
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    container_name: amdd_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"             # Évite conflit local
    environment:
      MYSQL_DATABASE: amdd_db
      MYSQL_ROOT_PASSWORD: root  # ✅ Mot de passe pour root
      # ❌ Supprime MYSQL_ALLOW_EMPTY_PASSWORD
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  dbdata: